export const weatherCodeGifs = {
  182: "/images/snow.png",
  377: "/images/snow.png",
  374: "/images/snow.png",
  365: "/images/snow.png",
  362: "/images/snow.png",
  350: "/images/snow.png",
  320: "/images/snow.png",
  317: "/images/snow.png",
  395: "/images/snow.png",
  392: "/images/snow.png",
  371: "/images/snow.png",
  368: "/images/snow.png",
  338: "/images/snow.png",
  335: "/images/snow.png",
  332: "/images/snow.png",
  329: "/images/snow.png",
  326: "/images/snow.png",
  323: "/images/snow.png",
  230: "/images/snow.png",
  227: "/images/snow.png",
  179: "/images/snow.png",
  389: "/images/lightning.png",
  386: "/images/lightning.png",
  200: "/images/lightning.png",
  113: "/images/sun.png",
  116: "/images/partly-cloudy.png",
  122: "/images/cloud.png",
  119: "/images/cloud.png",
  260: "/images/cloud.png",
  248: "/images/cloud.png",
  143: "/images/cloud.png",
  185: "/images/rain.png",
  359: "/images/rain.png",
  356: "/images/rain.png",
  353: "/images/rain.png",
  314: "/images/rain.png",
  311: "/images/rain.png",
  308: "/images/rain.png",
  305: "/images/rain.png",
  302: "/images/rain.png",
  299: "/images/rain.png",
  296: "/images/rain.png",
  293: "/images/rain.png",
  284: "/images/rain.png",
  281: "/images/rain.png",
  266: "/images/rain.png",
  263: "/images/rain.png",
  176: "/images/rain.png",
};

export default weatherCodeGifs;

// weatherCodes = {
//   snowing: [
//     {
//       code: 395,
//       description: "Moderate or heavy snow in area with thunder",
//       day: "wsymbol_0012_heavy_snow_showers",
//       night: "wsymbol_0028_heavy_snow_showers_night",
//     },
//     {
//       code: 392,
//       description: "Patchy light snow in area with thunder",
//       day: "wsymbol_0016_thundery_showers",
//       night: "wsymbol_0032_thundery_showers_night",
//     },
//     {
//       code: 371,
//       description: "Moderate or heavy snow showers",
//       day: "wsymbol_0012_heavy_snow_showers",
//       night: "wsymbol_0028_heavy_snow_showers_night",
//     },
//     {
//       code: 368,
//       description: "Light snow showers",
//       day: "wsymbol_0011_light_snow_showers",
//       night: "wsymbol_0027_light_snow_showers_night",
//     },
//     {
//       code: 338,
//       description: "Heavy snow",
//       day: "wsymbol_0020_cloudy_with_heavy_snow",
//       night: "wsymbol_0036_cloudy_with_heavy_snow_night",
//     },
//     {
//       code: 335,
//       description: "Patchy heavy snow",
//       day: "wsymbol_0012_heavy_snow_showers",
//       night: "wsymbol_0028_heavy_snow_showers_night",
//     },
//     {
//       code: 332,
//       description: "Moderate snow",
//       day: "wsymbol_0020_cloudy_with_heavy_snow",
//       night: "wsymbol_0036_cloudy_with_heavy_snow_night",
//     },
//     {
//       code: 329,
//       description: "Patchy moderate snow",
//       day: "wsymbol_0020_cloudy_with_heavy_snow",
//       night: "wsymbol_0036_cloudy_with_heavy_snow_night",
//     },
//     {
//       code: 326,
//       description: "Light snow",
//       day: "wsymbol_0011_light_snow_showers",
//       night: "wsymbol_0027_light_snow_showers_night",
//     },
//     {
//       code: 323,
//       description: "Patchy light snow",
//       day: "wsymbol_0011_light_snow_showers",
//       night: "wsymbol_0027_light_snow_showers_night",
//     },
//     {
//       code: 230,
//       description: "Blizzard",
//       day: "wsymbol_0020_cloudy_with_heavy_snow",
//       night: "wsymbol_0036_cloudy_with_heavy_snow_night",
//     },
//     {
//       code: 227,
//       description: "Blowing snow",
//       day: "wsymbol_0019_cloudy_with_light_snow",
//       night: "wsymbol_0035_cloudy_with_light_snow_night",
//     },
//     {
//       code: 179,
//       description: "Patchy snow nearby",
//       day: "wsymbol_0013_sleet_showers",
//       night: "wsymbol_0029_sleet_showers_night",
//     },
//   ],
//   lightning: [
//     {
//       code: 389,
//       description: "Moderate or heavy rain in area with thunder",
//       day: "wsymbol_0024_thunderstorms",
//       night: "wsymbol_0040_thunderstorms_night",
//     },
//     {
//       code: 386,
//       description: "Patchy light rain in area with thunder",
//       day: "wsymbol_0016_thundery_showers",
//       night: "wsymbol_0032_thundery_showers_night",
//     },
//     {
//       code: 200,
//       description: "Thundery outbreaks in nearby",
//       day: "wsymbol_0016_thundery_showers",
//       night: "wsymbol_0032_thundery_showers_night",
//     },
//   ],
//   sunny: [
//     {
//       code: 113,
//       description: "Clear/Sunny",
//       day: "wsymbol_0001_sunny",
//       night: "wsymbol_0008_clear_sky_night",
//     },
//   ],
//   partlyCloudy: [
//     {
//       code: 116,
//       description: "Partly Cloudy",
//       day: "wsymbol_0002_sunny_intervals",
//       night: "wsymbol_0008_clear_sky_night",
//     },
//   ],

//   cloudy: [
//     {
//       code: 122,
//       description: "Overcast",
//       day: "wsymbol_0004_black_low_cloud",
//       night: "wsymbol_0004_black_low_cloud",
//     },
//     {
//       code: 119,
//       description: "Cloudy",
//       day: "wsymbol_0003_white_cloud",
//       night: "wsymbol_0004_black_low_cloud",
//     },
//   ],
//   raining: [
//     {
//       code: 359,
//       description: "Torrential rain shower",
//       day: "wsymbol_0018_cloudy_with_heavy_rain",
//       night: "wsymbol_0034_cloudy_with_heavy_rain_night",
//     },
//     {
//       code: 356,
//       description: "Moderate or heavy rain shower",
//       day: "wsymbol_0010_heavy_rain_showers",
//       night: "wsymbol_0026_heavy_rain_showers_night",
//     },
//     {
//       code: 353,
//       description: "Light rain shower",
//       day: "wsymbol_0009_light_rain_showers",
//       night: "wsymbol_0025_light_rain_showers_night",
//     },
//     {
//       code: 314,
//       description: "Moderate or Heavy freezing rain",
//       day: "wsymbol_0021_cloudy_with_sleet",
//       night: "wsymbol_0037_cloudy_with_sleet_night",
//     },
//     {
//       code: 311,
//       description: "Light freezing rain",
//       day: "wsymbol_0021_cloudy_with_sleet",
//       night: "wsymbol_0037_cloudy_with_sleet_night",
//     },
//     {
//       code: 308,
//       description: "Heavy rain",
//       day: "wsymbol_0018_cloudy_with_heavy_rain",
//       night: "wsymbol_0034_cloudy_with_heavy_rain_night",
//     },
//     {
//       code: 305,
//       description: "Heavy rain at times",
//       day: "wsymbol_0010_heavy_rain_showers",
//       night: "wsymbol_0026_heavy_rain_showers_night",
//     },
//     {
//       code: 302,
//       description: "Moderate rain",
//       day: "wsymbol_0018_cloudy_with_heavy_rain",
//       night: "wsymbol_0034_cloudy_with_heavy_rain_night",
//     },
//     {
//       code: 299,
//       description: "Moderate rain at times",
//       day: "wsymbol_0010_heavy_rain_showers",
//       night: "wsymbol_0026_heavy_rain_showers_night",
//     },
//     {
//       code: 296,
//       description: "Light rain",
//       day: "wsymbol_0017_cloudy_with_light_rain",
//       night: "wsymbol_0025_light_rain_showers_night",
//     },
//     {
//       code: 293,
//       description: "Patchy light rain",
//       day: "wsymbol_0017_cloudy_with_light_rain",
//       night: "wsymbol_0033_cloudy_with_light_rain_night",
//     },
//     {
//       code: 284,
//       description: "Heavy freezing drizzle",
//       day: "wsymbol_0021_cloudy_with_sleet",
//       night: "wsymbol_0037_cloudy_with_sleet_night",
//     },
//     {
//       code: 281,
//       description: "Freezing drizzle",
//       day: "wsymbol_0021_cloudy_with_sleet",
//       night: "wsymbol_0037_cloudy_with_sleet_night",
//     },
//     {
//       code: 266,
//       description: "Light drizzle",
//       day: "wsymbol_0017_cloudy_with_light_rain",
//       night: "wsymbol_0033_cloudy_with_light_rain_night",
//     },
//     {
//       code: 263,
//       description: "Patchy light drizzle",
//       day: "wsymbol_0009_light_rain_showers",
//       night: "wsymbol_0025_light_rain_showers_night",
//     },
//   ],
//   rest: [
//     {
//       code: 377,
//       description: "Moderate or heavy showers of ice pellets",
//       day: "wsymbol_0021_cloudy_with_sleet",
//       night: "wsymbol_0037_cloudy_with_sleet_night",
//     },
//     {
//       code: 374,
//       description: "Light showers of ice pellets",
//       day: "wsymbol_0013_sleet_showers",
//       night: "wsymbol_0029_sleet_showers_night",
//     },
//     {
//       code: 365,
//       description: "Moderate or heavy sleet showers",
//       day: "wsymbol_0013_sleet_showers",
//       night: "wsymbol_0029_sleet_showers_night",
//     },
//     {
//       code: 362,
//       description: "Light sleet showers",
//       day: "wsymbol_0013_sleet_showers",
//       night: "wsymbol_0029_sleet_showers_night",
//     },

//     {
//       code: 350,
//       description: "Ice pellets",
//       day: "wsymbol_0021_cloudy_with_sleet",
//       night: "wsymbol_0037_cloudy_with_sleet_night",
//     },
//     {
//       code: 320,
//       description: "Moderate or heavy sleet",
//       day: "wsymbol_0019_cloudy_with_light_snow",
//       night: "wsymbol_0035_cloudy_with_light_snow_night",
//     },
//     {
//       code: 317,
//       description: "Light sleet",
//       day: "wsymbol_0021_cloudy_with_sleet",
//       night: "wsymbol_0037_cloudy_with_sleet_night",
//     },

//     {
//       code: 260,
//       description: "Freezing fog",
//       day: "wsymbol_0007_fog",
//       night: "wsymbol_0007_fog",
//     },
//     {
//       code: 248,
//       description: "Fog",
//       day: "wsymbol_0007_fog",
//       night: "wsymbol_0007_fog",
//     },
//     {
//       code: 185,
//       description: "Patchy freezing drizzle nearby",
//       day: "wsymbol_0021_cloudy_with_sleet",
//       night: "wsymbol_0037_cloudy_with_sleet_night",
//     },
//     {
//       code: 182,
//       description: "Patchy sleet nearby",
//       day: "wsymbol_0021_cloudy_with_sleet",
//       night: "wsymbol_0037_cloudy_with_sleet_night",
//     },
//     {
//       code: 176,
//       description: "Patchy rain nearby",
//       day: "wsymbol_0009_light_rain_showers",
//       night: "wsymbol_0025_light_rain_showers_night",
//     },
//     {
//       code: 143,
//       description: "Mist",
//       day: "wsymbol_0006_mist",
//       night: "wsymbol_0006_mist",
//     },
//   ],
// };
