export const weatherCodeImages = {
  182: { day: "/images/snow.png", night: "/images/snow.png" },
  377: { day: "/images/snow.png", night: "/images/snow.png" },
  374: { day: "/images/snow.png", night: "/images/snow.png" },
  365: { day: "/images/snow.png", night: "/images/snow.png" },
  362: { day: "/images/snow.png", night: "/images/snow.png" },
  350: { day: "/images/snow.png", night: "/images/snow.png" },
  320: { day: "/images/snow.png", night: "/images/snow.png" },
  317: { day: "/images/snow.png", night: "/images/snow.png" },
  395: { day: "/images/snow.png", night: "/images/snow.png" },
  392: { day: "/images/snow.png", night: "/images/snow.png" },
  371: { day: "/images/snow.png", night: "/images/snow.png" },
  368: { day: "/images/snow.png", night: "/images/snow.png" },
  338: { day: "/images/snow.png", night: "/images/snow.png" },
  335: { day: "/images/snow.png", night: "/images/snow.png" },
  332: { day: "/images/snow.png", night: "/images/snow.png" },
  329: { day: "/images/snow.png", night: "/images/snow.png" },
  326: { day: "/images/snow.png", night: "/images/snow.png" },
  323: { day: "/images/snow.png", night: "/images/snow.png" },
  230: { day: "/images/snow.png", night: "/images/snow.png" },
  227: { day: "/images/snow.png", night: "/images/snow.png" },
  179: { day: "/images/snow.png", night: "/images/snow.png" },
  389: { day: "/images/lightning.png", night: "/images/lightning.png" },
  386: { day: "/images/lightning.png", night: "/images/lightning.png" },
  200: { day: "/images/lightning.png", night: "/images/lightning.png" },
  113: { day: "/images/sun.png", night: "/images/moon.png" },
  116: { day: "/images/partly-cloudy.png", night: "/images/partly-cloudy.png" },
  122: { day: "/images/cloud.png", night: "/images/cloud.png" },
  119: { day: "/images/cloud.png", night: "/images/cloud.png" },
  260: { day: "/images/cloud.png", night: "/images/cloud.png" },
  248: { day: "/images/cloud.png", night: "/images/cloud.png" },
  143: { day: "/images/cloud.png", night: "/images/cloud.png" },
  185: { day: "/images/rain.png", night: "/images/rain.png" },
  359: { day: "/images/rain.png", night: "/images/rain.png" },
  356: { day: "/images/rain.png", night: "/images/rain.png" },
  353: { day: "/images/rain.png", night: "/images/rain.png" },
  314: { day: "/images/rain.png", night: "/images/rain.png" },
  311: { day: "/images/rain.png", night: "/images/rain.png" },
  308: { day: "/images/rain.png", night: "/images/rain.png" },
  305: { day: "/images/rain.png", night: "/images/rain.png" },
  302: { day: "/images/rain.png", night: "/images/rain.png" },
  299: { day: "/images/rain.png", night: "/images/rain.png" },
  296: { day: "/images/rain.png", night: "/images/rain.png" },
  293: { day: "/images/rain.png", night: "/images/rain.png" },
  284: { day: "/images/rain.png", night: "/images/rain.png" },
  281: { day: "/images/rain.png", night: "/images/rain.png" },
  266: { day: "/images/rain.png", night: "/images/rain.png" },
  263: { day: "/images/rain.png", night: "/images/rain.png" },
  176: { day: "/images/rain.png", night: "/images/rain.png" },
};

export default weatherCodeImages;

// weatherCodes = {
//   snowing: [
//     {
//       code: 395,
//       description: "Moderate or heavy snow in area with thunder",
//       day: "wsymbol_0012_heavy_snow_showers",
//       night: "wsymbol_0028_heavy_snow_showers_night",
//     },
//     {
//       code: 392,
//       description: "Patchy light snow in area with thunder",
//       day: "wsymbol_0016_thundery_showers",
//       night: "wsymbol_0032_thundery_showers_night",
//     },
//     {
//       code: 371,
//       description: "Moderate or heavy snow showers",
//       day: "wsymbol_0012_heavy_snow_showers",
//       night: "wsymbol_0028_heavy_snow_showers_night",
//     },
//     {
//       code: 368,
//       description: "Light snow showers",
//       day: "wsymbol_0011_light_snow_showers",
//       night: "wsymbol_0027_light_snow_showers_night",
//     },
//     {
//       code: 338,
//       description: "Heavy snow",
//       day: "wsymbol_0020_cloudy_with_heavy_snow",
//       night: "wsymbol_0036_cloudy_with_heavy_snow_night",
//     },
//     {
//       code: 335,
//       description: "Patchy heavy snow",
//       day: "wsymbol_0012_heavy_snow_showers",
//       night: "wsymbol_0028_heavy_snow_showers_night",
//     },
//     {
//       code: 332,
//       description: "Moderate snow",
//       day: "wsymbol_0020_cloudy_with_heavy_snow",
//       night: "wsymbol_0036_cloudy_with_heavy_snow_night",
//     },
//     {
//       code: 329,
//       description: "Patchy moderate snow",
//       day: "wsymbol_0020_cloudy_with_heavy_snow",
//       night: "wsymbol_0036_cloudy_with_heavy_snow_night",
//     },
//     {
//       code: 326,
//       description: "Light snow",
//       day: "wsymbol_0011_light_snow_showers",
//       night: "wsymbol_0027_light_snow_showers_night",
//     },
//     {
//       code: 323,
//       description: "Patchy light snow",
//       day: "wsymbol_0011_light_snow_showers",
//       night: "wsymbol_0027_light_snow_showers_night",
//     },
//     {
//       code: 230,
//       description: "Blizzard",
//       day: "wsymbol_0020_cloudy_with_heavy_snow",
//       night: "wsymbol_0036_cloudy_with_heavy_snow_night",
//     },
//     {
//       code: 227,
//       description: "Blowing snow",
//       day: "wsymbol_0019_cloudy_with_light_snow",
//       night: "wsymbol_0035_cloudy_with_light_snow_night",
//     },
//     {
//       code: 179,
//       description: "Patchy snow nearby",
//       day: "wsymbol_0013_sleet_showers",
//       night: "wsymbol_0029_sleet_showers_night",
//     },
//   ],
//   lightning: [
//     {
//       code: 389,
//       description: "Moderate or heavy rain in area with thunder",
//       day: "wsymbol_0024_thunderstorms",
//       night: "wsymbol_0040_thunderstorms_night",
//     },
//     {
//       code: 386,
//       description: "Patchy light rain in area with thunder",
//       day: "wsymbol_0016_thundery_showers",
//       night: "wsymbol_0032_thundery_showers_night",
//     },
//     {
//       code: 200,
//       description: "Thundery outbreaks in nearby",
//       day: "wsymbol_0016_thundery_showers",
//       night: "wsymbol_0032_thundery_showers_night",
//     },
//   ],
//   sunny: [
//     {
//       code: 113,
//       description: "Clear/Sunny",
//       day: "wsymbol_0001_sunny",
//       night: "wsymbol_0008_clear_sky_night",
//     },
//   ],
//   partlyCloudy: [
//     {
//       code: 116,
//       description: "Partly Cloudy",
//       day: "wsymbol_0002_sunny_intervals",
//       night: "wsymbol_0008_clear_sky_night",
//     },
//   ],

//   cloudy: [
//     {
//       code: 122,
//       description: "Overcast",
//       day: "wsymbol_0004_black_low_cloud",
//       night: "wsymbol_0004_black_low_cloud",
//     },
//     {
//       code: 119,
//       description: "Cloudy",
//       day: "wsymbol_0003_white_cloud",
//       night: "wsymbol_0004_black_low_cloud",
//     },
//   ],
//   raining: [
//     {
//       code: 359,
//       description: "Torrential rain shower",
//       day: "wsymbol_0018_cloudy_with_heavy_rain",
//       night: "wsymbol_0034_cloudy_with_heavy_rain_night",
//     },
//     {
//       code: 356,
//       description: "Moderate or heavy rain shower",
//       day: "wsymbol_0010_heavy_rain_showers",
//       night: "wsymbol_0026_heavy_rain_showers_night",
//     },
//     {
//       code: 353,
//       description: "Light rain shower",
//       day: "wsymbol_0009_light_rain_showers",
//       night: "wsymbol_0025_light_rain_showers_night",
//     },
//     {
//       code: 314,
//       description: "Moderate or Heavy freezing rain",
//       day: "wsymbol_0021_cloudy_with_sleet",
//       night: "wsymbol_0037_cloudy_with_sleet_night",
//     },
//     {
//       code: 311,
//       description: "Light freezing rain",
//       day: "wsymbol_0021_cloudy_with_sleet",
//       night: "wsymbol_0037_cloudy_with_sleet_night",
//     },
//     {
//       code: 308,
//       description: "Heavy rain",
//       day: "wsymbol_0018_cloudy_with_heavy_rain",
//       night: "wsymbol_0034_cloudy_with_heavy_rain_night",
//     },
//     {
//       code: 305,
//       description: "Heavy rain at times",
//       day: "wsymbol_0010_heavy_rain_showers",
//       night: "wsymbol_0026_heavy_rain_showers_night",
//     },
//     {
//       code: 302,
//       description: "Moderate rain",
//       day: "wsymbol_0018_cloudy_with_heavy_rain",
//       night: "wsymbol_0034_cloudy_with_heavy_rain_night",
//     },
//     {
//       code: 299,
//       description: "Moderate rain at times",
//       day: "wsymbol_0010_heavy_rain_showers",
//       night: "wsymbol_0026_heavy_rain_showers_night",
//     },
//     {
//       code: 296,
//       description: "Light rain",
//       day: "wsymbol_0017_cloudy_with_light_rain",
//       night: "wsymbol_0025_light_rain_showers_night",
//     },
//     {
//       code: 293,
//       description: "Patchy light rain",
//       day: "wsymbol_0017_cloudy_with_light_rain",
//       night: "wsymbol_0033_cloudy_with_light_rain_night",
//     },
//     {
//       code: 284,
//       description: "Heavy freezing drizzle",
//       day: "wsymbol_0021_cloudy_with_sleet",
//       night: "wsymbol_0037_cloudy_with_sleet_night",
//     },
//     {
//       code: 281,
//       description: "Freezing drizzle",
//       day: "wsymbol_0021_cloudy_with_sleet",
//       night: "wsymbol_0037_cloudy_with_sleet_night",
//     },
//     {
//       code: 266,
//       description: "Light drizzle",
//       day: "wsymbol_0017_cloudy_with_light_rain",
//       night: "wsymbol_0033_cloudy_with_light_rain_night",
//     },
//     {
//       code: 263,
//       description: "Patchy light drizzle",
//       day: "wsymbol_0009_light_rain_showers",
//       night: "wsymbol_0025_light_rain_showers_night",
//     },
//   ],
//   rest: [
//     {
//       code: 377,
//       description: "Moderate or heavy showers of ice pellets",
//       day: "wsymbol_0021_cloudy_with_sleet",
//       night: "wsymbol_0037_cloudy_with_sleet_night",
//     },
//     {
//       code: 374,
//       description: "Light showers of ice pellets",
//       day: "wsymbol_0013_sleet_showers",
//       night: "wsymbol_0029_sleet_showers_night",
//     },
//     {
//       code: 365,
//       description: "Moderate or heavy sleet showers",
//       day: "wsymbol_0013_sleet_showers",
//       night: "wsymbol_0029_sleet_showers_night",
//     },
//     {
//       code: 362,
//       description: "Light sleet showers",
//       day: "wsymbol_0013_sleet_showers",
//       night: "wsymbol_0029_sleet_showers_night",
//     },

//     {
//       code: 350,
//       description: "Ice pellets",
//       day: "wsymbol_0021_cloudy_with_sleet",
//       night: "wsymbol_0037_cloudy_with_sleet_night",
//     },
//     {
//       code: 320,
//       description: "Moderate or heavy sleet",
//       day: "wsymbol_0019_cloudy_with_light_snow",
//       night: "wsymbol_0035_cloudy_with_light_snow_night",
//     },
//     {
//       code: 317,
//       description: "Light sleet",
//       day: "wsymbol_0021_cloudy_with_sleet",
//       night: "wsymbol_0037_cloudy_with_sleet_night",
//     },

//     {
//       code: 260,
//       description: "Freezing fog",
//       day: "wsymbol_0007_fog",
//       night: "wsymbol_0007_fog",
//     },
//     {
//       code: 248,
//       description: "Fog",
//       day: "wsymbol_0007_fog",
//       night: "wsymbol_0007_fog",
//     },
//     {
//       code: 185,
//       description: "Patchy freezing drizzle nearby",
//       day: "wsymbol_0021_cloudy_with_sleet",
//       night: "wsymbol_0037_cloudy_with_sleet_night",
//     },
//     {
//       code: 182,
//       description: "Patchy sleet nearby",
//       day: "wsymbol_0021_cloudy_with_sleet",
//       night: "wsymbol_0037_cloudy_with_sleet_night",
//     },
//     {
//       code: 176,
//       description: "Patchy rain nearby",
//       day: "wsymbol_0009_light_rain_showers",
//       night: "wsymbol_0025_light_rain_showers_night",
//     },
//     {
//       code: 143,
//       description: "Mist",
//       day: "wsymbol_0006_mist",
//       night: "wsymbol_0006_mist",
//     },
//   ],
// };
